from typing import List
from dataclasses import dataclass
from enum import Enum
from .Regions import Regions, HbkRegion


class HbkLocationType(Enum):
    AttackChai = 1
    AttackPeppermint = 2
    AttackMacaron = 3
    AttackKorsica = 4
    SpecialAttack = 5
    StoreItem = 6
    Chip = 7
    Collectible = 8
    VLog = 9
    SPECTRA = 10
    Graffiti = 11
    Ability = 12
    Partner = 13
    SubMission = 14
    TrackComplete = 15
    NPCItem = 16


@dataclass
class HbkLocation:
    name: str
    region: HbkRegion
    loc_type: HbkLocationType
    loc_str: str


location_list: List[HbkLocation] = [
    HbkLocation("Store - Attacks: Echo Splash", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.XYXXX"),
    HbkLocation("Store - Attacks: Tune Up", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.XX-XXX"),
    HbkLocation("Store - Attacks: Stomp Box", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.YXY"),
    HbkLocation("Store - Attacks: Arpeggio Stab", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.XXYYY"),
    HbkLocation("Store - Attacks: Pickup Crash", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.YYX"),
    HbkLocation("Store - Attacks: Harmonic Beam", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.AirXYYY"),
    HbkLocation("Store - Attacks: Compressor Slam", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.AirXYXY"),
    HbkLocation("Store - Attacks: Shred", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.XmY"),
    HbkLocation("Store - Attacks: Staccato Launch", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.C-X"),
    HbkLocation("Store - Attacks: Gain Tornado", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.C-Y"),
    HbkLocation("Store - Attacks: Quick Beat Hit", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.Q-X"),
    HbkLocation("Store - Attacks: Steal Counter", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Combo.Q-Y"),
    HbkLocation("Store - Attacks: Magnet Backstab", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Ability.MagnetBackstab"),
    HbkLocation("Store - Attacks: Air Parry", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Ability.AirParry"),
    HbkLocation("Store - Attacks: Directional Parry", Regions.s, HbkLocationType.AttackChai, "Store/Inventory.Ability.DirectionalParry"),
    HbkLocation("Store - Attacks: Switch Kicker", Regions.s, HbkLocationType.AttackPeppermint, "Store/Inventory.Partner.JamCombo.PG01"),
    HbkLocation("Store - Attacks: Master Blaster", Regions.s, HbkLocationType.AttackPeppermint, "Store/Inventory.Partner.JamCombo.PA01"),
    HbkLocation("Store - Attacks: Cannon Spike", Regions.s, HbkLocationType.AttackPeppermint, "Store/Inventory.Partner.Charge.P01"),
    HbkLocation("Store - Attacks: Kick Shot", Regions.s, HbkLocationType.AttackPeppermint, "Store/Inventory.Partner.Counter.P01"),
    HbkLocation("Store - Attacks: Double Bass Drop", Regions.s, HbkLocationType.AttackMacaron, "Store/Inventory.Partner.JamCombo.MG01"),
    HbkLocation("Store - Attacks: High Strung", Regions.s, HbkLocationType.AttackMacaron, "Store/Inventory.Partner.JamCombo.MA01"),
    HbkLocation("Store - Attacks: Gravity Well", Regions.s, HbkLocationType.AttackMacaron, "Store/Inventory.Partner.Charge.M01"),
    HbkLocation("Store - Attacks: Love Tap", Regions.s, HbkLocationType.AttackMacaron, "Store/Inventory.Partner.Counter.M01"),
    HbkLocation("Store - Attacks: High Security Risk", Regions.s, HbkLocationType.AttackKorsica, "Store/Inventory.Partner.JamCombo.KG01"),
    HbkLocation("Store - Attacks: Tornado Lift", Regions.s, HbkLocationType.AttackKorsica, "Store/Inventory.Partner.JamCombo.KA01"),
    HbkLocation("Store - Attacks: Korsica Typhoon", Regions.s, HbkLocationType.AttackKorsica, "Store/Inventory.Partner.Charge.K01"),
    HbkLocation("Store - Attacks: High Alert", Regions.s, HbkLocationType.AttackKorsica, "Store/Inventory.Partner.Counter.K01"),

    HbkLocation("Store - Special Attacks: Guitar Ride", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Pick Me Up!", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Pick Slide", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: High Pitch Punch", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Air Guitar", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Rip and Tear", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Double Riff", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Barrier Wall", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Twin Assault", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Steal the Show", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Holo-Chai", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Hibiki!", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: Overdrive Slash", Regions.s, HbkLocationType.SpecialAttack, ""),
    HbkLocation("Store - Special Attacks: 808-Gigawatt Cat-attack", Regions.s, HbkLocationType.SpecialAttack, ""),

    HbkLocation("Store - Items: Life Gauge #1", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Life Gauge #2", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Life Gauge #3", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Life Gauge #4", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Life Gauge #5", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Life Gauge #6", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Electric Reverb Core #1", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Electric Reverb Core #2", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Electric Reverb Core #3", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Health Tank", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Additional Chip Slot #1", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Additional Chip Slot #2", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Additional Chip Slot #3", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Additional Chip Slot #4", Regions.s, HbkLocationType.StoreItem, ""),
    HbkLocation("Store - Items: Special Attack Slot Upgrade", Regions.s, HbkLocationType.StoreItem, ""),

    HbkLocation("Store - Chips: Peppermint Compatibility Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Compatibility Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Compatibility Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Health Kick Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Health Kick Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Health Kick Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Battery Magnet Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Battery Magnet Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Battery Magnet Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Rhythm Meter Rush Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Rhythm Meter Rush Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Rhythm Meter Rush Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Parry Health Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Parry Health Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Parry Health Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Parry Charge Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Parry Charge Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Parry Charge Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Invincible D-Parry Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Invincible D-Parry Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Invincible D-Parry Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Damage Rebound D-Parry Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Damage Rebound D-Parry Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Damage Rebound D-Parry Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Combo Holder Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Combo Holder Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Combo Holder Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Rhythm Dodge Pull Plus Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Rhythm Dodge Pull Plus Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Rhythm Dodge Pull Plus Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Rhythm Dodge Pull Cancel", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Shock Advantage Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Shock Advantage Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Shock Advantage Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Shock Jump Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Shock Jump Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Peppermint Shock Jump Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron Compatibility Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron Compatibility Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron Compatibility Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron's Lucky Punch Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron's Lucky Punch Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron's Lucky Punch Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron's Aftershock Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron's Aftershock Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Macaron's Aftershock Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Korsica Compatibility Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Korsica Compatibility Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Korsica Compatibility Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Super High Alert Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Super High Alert Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Super High Alert Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Korsica Stun Extend Lv.1", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Korsica Stun Extend Lv.2", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Korsica Stun Extend Lv.3", Regions.s, HbkLocationType.Chip, ""),
    HbkLocation("Store - Chips: Chip Sense", Regions.s, HbkLocationType.Chip, ""),

    HbkLocation("Track 1: Item from SEB-AAA", Regions.t1, HbkLocationType.NPCItem, ""),
    HbkLocation("Track 1: Life Gauge Piece #1", Regions.t1, HbkLocationType.Collectible, "St01/LifeCoreItem_BP1"),
    HbkLocation("Track 1: VLog \"TO ALL EMPLOYEES!\"", Regions.t1, HbkLocationType.VLog, "Inventory.File.VLog.0000"),
    HbkLocation("Track 1: Life Gauge Piece #2", Regions.t1, HbkLocationType.Collectible, "St01/LifeCoreItem_BP2"),
    HbkLocation("Track 1: SPECTRA Challenge Room", Regions.t1, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 1: VLog \"Battery Pack Production\"", Regions.t1, HbkLocationType.VLog, "Inventory.File.VLog.0010"),
    HbkLocation("Track 1: VLog \"Old-gen EOL Reminder\"", Regions.t1, HbkLocationType.VLog, "Inventory.File.VLog.0020"),
    HbkLocation("Track 1: Broken Piece of a Health Tank", Regions.t1, HbkLocationType.Collectible, "St01/np0600_BP1"),
    HbkLocation("Track 1: Electric Reverb Core Piece", Regions.t1, HbkLocationType.Collectible, "St01/ReverbPieceItem_BP_2"),
    HbkLocation("Track 1: Graffiti #1 (Tower)", Regions.t1, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 1: Broken Armstrong Circuit #1", Regions.t1, HbkLocationType.Collectible, "St01/np0600_BP2_2"),
    HbkLocation("Track 1: VLog \"RE:RE:RE:RE:RE:RE:RE: Get on this!\"", Regions.t1, HbkLocationType.VLog, "Inventory.File.VLog.0030"),
    HbkLocation("Track 1: VLog \"O5-KAR Unit Musings\"", Regions.t1, HbkLocationType.VLog, "Inventory.File.VLog.0040"),
    HbkLocation("Track 1: Broken Armstrong Circuit #2", Regions.t1, HbkLocationType.Collectible, "St01/CircuitItem_BP1"),
    HbkLocation("Track 1: Graffiti #2 (Crane)", Regions.t1, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 1: Life Gauge Piece #3", Regions.t1, HbkLocationType.Collectible, "St01/LifeCoreItem_BP3_2"),
    HbkLocation("Track 1: Completed", Regions.t1, HbkLocationType.TrackComplete, "cs0180_00"),

    HbkLocation("Track 2: VLog \"Unsent Complaint\"", Regions.t2, HbkLocationType.VLog, "Inventory.File.VLog.0050"),
    HbkLocation("Track 2: Electric Reverb Core Piece #1", Regions.t2, HbkLocationType.Collectible, "St02/ReverbPieceItem_BP1"),
    HbkLocation("Track 2: VLog \"HR Auto-Surveillance Recording\"", Regions.t2, HbkLocationType.VLog, "Inventory.File.VLog.0060"),
    HbkLocation("Track 2: Unlock Magnet", Regions.t2, HbkLocationType.Ability, ""),
    HbkLocation("Track 2: Broken Armstrong Circuit #1", Regions.t2, HbkLocationType.Collectible, "St02/CircuitItem_BP1"),
    HbkLocation("Track 2: VLog \"HR Claim #324839028555180850195\"", Regions.t2, HbkLocationType.VLog, "Inventory.File.VLog.0070"),
    HbkLocation("Track 2: Rock Comic", Regions.t2, HbkLocationType.Collectible, "St02/RockComic_A_BP_2"),
    HbkLocation("Track 2: Broken Armstrong Circuit #2", Regions.t2, HbkLocationType.Collectible, "St02/CircuitItem_BP2"),
    HbkLocation("Track 2: Graffiti #1 (Robot Portrait)", Regions.t2, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 2: Graffiti #2 (Claw)", Regions.t2, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 2: Electric Reverb Core Piece #2", Regions.t2, HbkLocationType.Collectible, "St02/ReverbPieceItem_BP2_5"),
    HbkLocation("Track 2: Life Gauge Piece #1", Regions.t2, HbkLocationType.Collectible, "St02/LifeCoreItem_BP3_2"),
    HbkLocation("Track 2: Broken Armstrong Circuit #3", Regions.t2, HbkLocationType.Collectible, "St02/np0600_BP1"),
    HbkLocation("Track 2: Broken Armstrong Circuit #4", Regions.t2, HbkLocationType.Collectible, "St02/CircuitItem_BP3"),
    HbkLocation("Track 2: VLog \"Tram Line Issues\"", Regions.t2, HbkLocationType.VLog, "Inventory.File.VLog.0080"),
    HbkLocation("Track 2: Unlock Peppermint", Regions.t2, HbkLocationType.Partner, ""),
    HbkLocation("Track 2: VLog \"Introducing \"The Arrow!\"\"", Regions.t2, HbkLocationType.VLog, "Inventory.File.VLog.0090"),
    HbkLocation("Track 2: SPECTRA Challenge Room", Regions.t2, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 2: Broken Armstrong Circuit #5", Regions.t2, HbkLocationType.Collectible, "St02/np0600_BP2_2"),
    HbkLocation("Track 2: Life Gauge Piece #2", Regions.t2, HbkLocationType.Collectible, "St02/np0600_BP3"),
    HbkLocation("Track 2: Sub-mission (Pigeons scattered!)", Regions.t2, HbkLocationType.SubMission, ""), #Life Gauge Piece
    HbkLocation("Track 2: VLog \"Behind the Showmanship: Sitdown with Rekka\"", Regions.t2, HbkLocationType.VLog, "Inventory.File.VLog.0100"),
    HbkLocation("Track 2: Graffiti #3 (Rekka)", Regions.t2, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 2: Completed", Regions.t2, HbkLocationType.TrackComplete, "cs0245_00"),

    HbkLocation("Track 3: VLog \"R&D Service Log: Part 1\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0110"),
    HbkLocation("Track 3: Broken Armstrong Circuit #1", Regions.t3, HbkLocationType.Collectible, "St03/CircuitItem_BP1"),
    HbkLocation("Track 3: Broken Armstrong Circuit #2", Regions.t3, HbkLocationType.Collectible, "St03/CircuitItem_BP2"),
    HbkLocation("Track 3: Broken Piece of a Health Tank", Regions.t3, HbkLocationType.Collectible, "St03/LifeTankPieceItem_BP"),
    HbkLocation("Track 3: Broken Armstrong Circuit #3", Regions.t3, HbkLocationType.Collectible, "St03/CircuitItem_BP3"),
    HbkLocation("Track 3: VLog \"R&D Service Log: Part 2\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0120"),
    HbkLocation("Track 3: Electric Reverb Core Piece #1", Regions.t3, HbkLocationType.Collectible, "St03/ReverbPieceItem_BP2_2"), #this might be incorrect
    HbkLocation("Track 3: Graffiti #1 (Flowers)", Regions.t3, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 3: VLog \"R&D Service Log: Part 3\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0130"),
    HbkLocation("Track 3: Life Gauge Piece #1", Regions.t3, HbkLocationType.Collectible, "St03/np0600_BP_2"),
    HbkLocation("Track 3: VLog \"R&D Service Log: Part 4\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0140"),
    HbkLocation("Track 3: VLog \"Zanzo's Order Request\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0150"),
    HbkLocation("Track 3: Broken Armstrong Circuit #4", Regions.t3, HbkLocationType.Collectible, "St03/CircuitItem_BP5"),
    HbkLocation("Track 3: Broken Armstrong Circuit #5", Regions.t3, HbkLocationType.Collectible, "St03/CircuitItem_BP6"),
    HbkLocation("Track 3: Graffiti #2 (Volcano)", Regions.t3, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 3: VLog \"LU-C1LLE Self-Therapy Journal\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0160"),
    HbkLocation("Track 3: VLog \"Barrier Technology Test Results\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0170"),
    HbkLocation("Track 3: VLog \"Punch-to-face Test Results\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0180"),
    HbkLocation("Track 3: Electric Reverb Core Piece #2", Regions.t3, HbkLocationType.Collectible, "St03/ReverbPieceItem_BP_2"),
    HbkLocation("Track 3: Unlock Parry", Regions.t3, HbkLocationType.Ability, ""),
    HbkLocation("Track 3: Broken Armstrong Circuit #6", Regions.t3, HbkLocationType.Collectible, "St03/CircuitItem_BP4"),
    HbkLocation("Track 3: VLog \"Offensive Capabilites Test\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0190"),
    HbkLocation("Track 3: Graffiti #3 (Zanzo)", Regions.t3, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 3: VLog \"Barrier Umbrella Test\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0200"),
    HbkLocation("Track 3: Life Gauge Piece #2", Regions.t3, HbkLocationType.Collectible, "St03/LifeCoreItem_BP1"),
    HbkLocation("Track 3: Rock Comic", Regions.t3, HbkLocationType.Collectible, "St03/RockComic_B_BP_3"),
    HbkLocation("Track 3: VLog \"Test Lab Assistance Mail\"", Regions.t3, HbkLocationType.VLog, "Inventory.File.VLog.0210"),
    HbkLocation("Track 3: SPECTRA Challenge Room", Regions.t3, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 3: Life Gauge Piece #3", Regions.t3, HbkLocationType.Collectible, "St03/LifeCoreItem_BP2_2"),
    HbkLocation("Track 3: Completed", Regions.t3, HbkLocationType.TrackComplete, "cs0315_00"),

    HbkLocation("Track 4: Unlock Macaron", Regions.t4, HbkLocationType.Partner, ""),
    HbkLocation("Track 4: VLog \"Staffing Allocation Complaint\"", Regions.t4, HbkLocationType.VLog, "Inventory.File.VLog.0220"),
    HbkLocation("Track 4: Broken Armstrong Circuit #1", Regions.t4, HbkLocationType.Collectible, "St04/CircuitItem_BP1"),
    HbkLocation("Track 4: VLog \"Auto-Saved Private Message\"", Regions.t4, HbkLocationType.VLog, "Inventory.File.VLog.0230"),
    HbkLocation("Track 4: Broken Armstrong Circuit #2", Regions.t4, HbkLocationType.Collectible, "St04/CircuitItem_BP2"),
    HbkLocation("Track 4: VLog \"Disgruntled Decaf Revenge\"", Regions.t4, HbkLocationType.VLog, "Inventory.File.VLog.0240"),
    HbkLocation("Track 4: Broken Piece of a Health Tank #1", Regions.t4, HbkLocationType.Collectible, "St04/np0600_BP_2"),
    HbkLocation("Track 4: Life Gauge Piece #1", Regions.t4, HbkLocationType.Collectible, "St04/LifeCoreItem_BP1"),
    HbkLocation("Track 4: Broken Armstrong Circuit #3", Regions.t4, HbkLocationType.Collectible, "St04/CircuitItem_BP3"),
    HbkLocation("Track 4: Graffiti #1 (HG-0G)", Regions.t4, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 4: Broken Armstrong Circuit #4", Regions.t4, HbkLocationType.Collectible, "St04/CircuitItem_BP4_1"),
    HbkLocation("Track 4: SPECTRA Challenge Room", Regions.t4, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 4: Graffiti #2 (VARRT)", Regions.t4, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 4: Life Gauge Piece #2", Regions.t4, HbkLocationType.Collectible, "St04/LifeCoreItem_BP2"),
    HbkLocation("Track 4: Broken Armstrong Circuit #5", Regions.t4, HbkLocationType.Collectible, "St04/CircuitItem_BP5"),
    HbkLocation("Track 4: Broken Armstrong Circuit #6", Regions.t4, HbkLocationType.Collectible, "St04/CircuitItem_BP6"),
    HbkLocation("Track 4: VLog \"Development Mindfulness Checklist\"", Regions.t4, HbkLocationType.VLog, "Inventory.File.VLog.0250"),
    HbkLocation("Track 4: Broken Piece of a Health Tank #2", Regions.t4, HbkLocationType.Collectible, "St04/LifeTankPieceItem_BP2"),
    HbkLocation("Track 4: Life Gauge Piece #3", Regions.t4, HbkLocationType.Collectible, "St04/LifeCoreItem_BP3"),
    HbkLocation("Track 4: Completed", Regions.t4, HbkLocationType.TrackComplete, "cs0430_00"),

    HbkLocation("Track 5: VLog \"Defect Captured Email\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0260"),
    HbkLocation("Track 5: Life Gauge Piece #1", Regions.t5, HbkLocationType.Collectible, "St05/LifeCoreItem_BP1"),
    HbkLocation("Track 5: VLog \"Annoyed by Korsica FWD\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0270"),
    HbkLocation("Track 5: Graffiti #1 (Data Node)", Regions.t5, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 5: SPECTRA Challenge Room", Regions.t5, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 5: Broken Armstrong Circuit #1", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP1"),
    HbkLocation("Track 5: Broken Armstrong Circuit #2", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP3_2"),
    HbkLocation("Track 5: VLog \"Musings About Data Node\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0280"),
    HbkLocation("Track 5: Broken Armstrong Circuit #3", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP2_5"),
    HbkLocation("Track 5: Electric Reverb Core Piece #1", Regions.t5, HbkLocationType.Collectible, "St05/ReverbPieceItem_BP1"),
    HbkLocation("Track 5: VLog \"Poem by SCR-UB\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0290"),
    HbkLocation("Track 5: Rock Comic", Regions.t5, HbkLocationType.Collectible, "St05/RockComic_C_BP_2"),
    HbkLocation("Track 5: VLog \"Vandelay Game Studios?\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0300"),
    HbkLocation("Track 5: Life Gauge Piece #2", Regions.t5, HbkLocationType.Collectible, "St05/LifeCoreItem_BP3_4"), #this might be incorrect
    HbkLocation("Track 5: Broken Armstrong Circuit #4", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP5_2"),
    HbkLocation("Track 5: Electric Reverb Core Piece #2", Regions.t5, HbkLocationType.Collectible, "St05/ReverbPieceItem_BP2_8"),
    HbkLocation("Track 5: Broken Armstrong Circuit #5", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP6_8"), #this might be incorrect
    HbkLocation("Track 5: VLog \"Regarding Wing 1 Layout Complaints\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0310"),
    HbkLocation("Track 5: Broken Armstrong Circuit #6", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP7_5"),
    HbkLocation("Track 5: Broken Armstrong Circuit #7", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP8_2"),
    HbkLocation("Track 5: VLog \"FWD: Data Node Advice\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0320"),
    HbkLocation("Track 5: Broken Armstrong Circuit #8", Regions.t5, HbkLocationType.Collectible, "St05/CircuitItem_BP4_12"),
    HbkLocation("Track 5: VLog \"Korsica Complaints\"", Regions.t5, HbkLocationType.VLog, "Inventory.File.VLog.0330"),
    HbkLocation("Track 5: Sub-mission (Gathered drone packages!)", Regions.t5, HbkLocationType.SubMission, ""),#Life Gauge Piece
    HbkLocation("Track 5: Completed", Regions.t5, HbkLocationType.TrackComplete, "OnBattleEnded_St05_5"),

    HbkLocation("Track 6: Broken Armstrong Circuit", Regions.t6, HbkLocationType.Collectible, "St05b/CircuitItem_BP_2"),
    HbkLocation("Track 6: Graffiti (L.I.F.T.)", Regions.t6, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 6: VLog \"L.I.F.T. Construction Heads-up\"", Regions.t6, HbkLocationType.VLog, "Inventory.File.VLog.0340"),
    HbkLocation("Track 6: Completed", Regions.t5, HbkLocationType.TrackComplete, "cs0555_00"),

    HbkLocation("Track 7: VLog \"Platform Construction Note\"", Regions.t7, HbkLocationType.VLog, "Inventory.File.VLog.0350"),
    HbkLocation("Track 7: Broken Armstrong Circuit #1", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP1"),
    HbkLocation("Track 7: Broken Armstrong Circuit #2", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP2"),
    HbkLocation("Track 7: Life Gauge Piece #1", Regions.t7, HbkLocationType.Collectible, "St06/LifeCoreItem_BP1"),
    HbkLocation("Track 7: Broken Piece of a Health Tank", Regions.t7, HbkLocationType.Collectible, "St06/LifeTankPieceItem_BP"),
    HbkLocation("Track 7: Life Gauge Piece #2", Regions.t7, HbkLocationType.Collectible, "St06/np0600_BP_2"),
    HbkLocation("Track 7: Electric Reverb Core Piece", Regions.t7, HbkLocationType.Collectible, "St06/ReverbPieceItem_BP_2"),
    HbkLocation("Track 7: Broken Armstrong Circuit #3", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP3_2"),
    HbkLocation("Track 7: Broken Armstrong Circuit #4", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP4"),
    HbkLocation("Track 7: VLog \"Too Many Rooms\"", Regions.t7, HbkLocationType.VLog, "Inventory.File.VLog.0360"),
    HbkLocation("Track 7: Life Gauge Piece #3", Regions.t7, HbkLocationType.Collectible, "St06/LifeCoreItem_BP2_2"), #this might be incorrect
    HbkLocation("Track 7: Broken Armstrong Circuit #5", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP5"),
    HbkLocation("Track 7: SPECTRA Challenge Room", Regions.t7, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 7: VLog \"Suspicious Doors?\"", Regions.t7, HbkLocationType.VLog, "Inventory.File.VLog.0370"),
    HbkLocation("Track 7: Rock Comic", Regions.t7, HbkLocationType.Collectible, "St06/RockComic_D_BP_3"),
    HbkLocation("Track 7: Broken Armstrong Circuit #6", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP6"),
    HbkLocation("Track 7: VLog \"Data Node Dissatisfaction Mail\"", Regions.t7, HbkLocationType.VLog, "Inventory.File.VLog.0380"),
    HbkLocation("Track 7: VLog \"Pmidge Press Announcement\"", Regions.t7, HbkLocationType.VLog, "Inventory.File.VLog.0390"),
    HbkLocation("Track 7: Graffiti #1 (Korsica)", Regions.t7, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 7: Graffiti #2 (KEM-0N0)", Regions.t7, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 7: Broken Armstrong Circuit #7", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP7"),
    HbkLocation("Track 7: VLog \"Depressed Buttons\"", Regions.t7, HbkLocationType.VLog, "Inventory.File.VLog.0400"),
    HbkLocation("Track 7: Graffiti #3 (Lasers)", Regions.t7, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 7: Broken Armstrong Circuit #8", Regions.t7, HbkLocationType.Collectible, "St06/CircuitItem_BP8"),
    HbkLocation("Track 7: VLog \"Food Delivery Warning\"", Regions.t7, HbkLocationType.VLog, "Inventory.File.VLog.0410"),
    HbkLocation("Track 7: Completed", Regions.t7, HbkLocationType.TrackComplete, "cs0625_00"),

    HbkLocation("Track 8: VLog \"Armstrong Festival Marketing?\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0430"),
    HbkLocation("Track 8: VLog \"Project Armstrong Raffle Results\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0420"),
    HbkLocation("Track 8: Sub-mission (Find the golden can!)", Regions.t8, HbkLocationType.SubMission, ""),#Life Gauge Piece
    HbkLocation("Track 8: Broken Armstrong Circuit #1", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP1"),
    HbkLocation("Track 8: Graffiti #1 (Fireworks)", Regions.t8, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 8: Unlock Korsica", Regions.t8, HbkLocationType.Partner, ""),
    HbkLocation("Track 8: Broken Armstrong Circuit #2", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP2"),
    HbkLocation("Track 8: VLog \"Charging\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0440"),
    HbkLocation("Track 8: Broken Piece of a Health Tank #1", Regions.t8, HbkLocationType.Collectible, "St07/LifeTankPieceItem_BP1"),
    HbkLocation("Track 8: VLog \"Taking A Break In The Park\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0450"),
    HbkLocation("Track 8: Electric Reverb Core Piece #1", Regions.t8, HbkLocationType.Collectible, "St07/ReverbPieceItem_BP1"),
    HbkLocation("Track 8: Broken Armstrong Circuit #3", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP3"),
    HbkLocation("Track 8: Graffiti #2 (BL-1Z5)", Regions.t8, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 8: VLog \"SBR-001 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0490"),
    HbkLocation("Track 8: VLog \"GNR-020 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0460"),
    HbkLocation("Track 8: VLog \"ES-101 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0500"),
    HbkLocation("Track 8: VLog \"BES-102 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0470"),
    HbkLocation("Track 8: VLog \"BA-B00 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0510"),
    HbkLocation("Track 8: VLog \"BL-1Z5 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0480"),
    HbkLocation("Track 8: VLog \"Reminder to Reception\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0520"),
    HbkLocation("Track 8: VLog \"BRUT-1L Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0530"),
    HbkLocation("Track 8: VLog \"Our Community Helper: BA-B00\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0540"),
    HbkLocation("Track 8: VLog \"SEN-C0 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0550"),
    HbkLocation("Track 8: Graffiti #3 (Stage)", Regions.t8, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 8: Broken Armstrong Circuit #4", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP4"),
    HbkLocation("Track 8: Broken Armstrong Circuit #5", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP5"),
    HbkLocation("Track 8: Life Gauge Piece #1", Regions.t8, HbkLocationType.Collectible, "St07/LifeCoreItem_BP2"),
    HbkLocation("Track 8: VLog \"Disappointed O5-KAR\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0560"),
    HbkLocation("Track 8: Broken Piece of a Health Tank #2", Regions.t8, HbkLocationType.Collectible, "St07/LifeTankPieceItem_BP2"),
    HbkLocation("Track 8: VLog \"Water Generator Complaint\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0570"),
    HbkLocation("Track 8: Electric Reverb Core Piece #2", Regions.t8, HbkLocationType.Collectible, "St07/ReverbPieceItem_BP2"),
    HbkLocation("Track 8: Broken Armstrong Circuit #6", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP6"),
    HbkLocation("Track 8: VLog \"Display Complaints\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0580"),
    HbkLocation("Track 8: Broken Armstrong Circuit #7", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP7_0"),
    HbkLocation("Track 8: Life Gauge Piece #2", Regions.t8, HbkLocationType.Collectible, "St07/LifeCoreItem_BP3"),
    HbkLocation("Track 8: Graffiti #4 (Museum)", Regions.t8, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 8: VLog \"KEM-0N0 Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0590"),
    HbkLocation("Track 8: VLog \"SBR Development Display\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0600"),
    HbkLocation("Track 8: Life Gauge Piece #3", Regions.t8, HbkLocationType.Collectible, "St07/np0600_BP_2"),
    HbkLocation("Track 8: Broken Armstrong Circuit #8", Regions.t8, HbkLocationType.Collectible, "St07/CircuitItem_BP8"),
    HbkLocation("Track 8: VLog \"Door Musings from SCR-UB\"", Regions.t8, HbkLocationType.VLog, "Inventory.File.VLog.0610"),
    HbkLocation("Track 8: SPECTRA Challenge Room", Regions.t8, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 8: Completed", Regions.t8, HbkLocationType.TrackComplete, "cs0725_00"),

    HbkLocation("Track 9: Graffiti (Mimosa)", Regions.t9, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 9: Broken Armstrong Circuit #1", Regions.t9, HbkLocationType.Collectible, "St08/CircuitItem_BP1"),
    HbkLocation("Track 9: Life Gauge Piece", Regions.t9, HbkLocationType.Collectible, "St08/LifeCoreItem_BP_2"),
    HbkLocation("Track 9: VLog \"Armstrong Festival Briefing Notes\"", Regions.t9, HbkLocationType.VLog, "Inventory.File.VLog.0620"),
    HbkLocation("Track 9: VLog \"Mimosa's Rider\"", Regions.t9, HbkLocationType.VLog, "Inventory.File.VLog.0630"),
    HbkLocation("Track 9: Broken Armstrong Circuit #2", Regions.t9, HbkLocationType.Collectible, "St08/CircuitItem_BP2_2"),
    HbkLocation("Track 9: Completed", Regions.t9, HbkLocationType.TrackComplete, "cs0840_00"),

    HbkLocation("Track 10: VLog \"Cafeteria Menu\"", Regions.t10, HbkLocationType.VLog, "Inventory.File.VLog.0640"),
    HbkLocation("Track 10: VLog \"Vandelay Grammar Check\"", Regions.t10, HbkLocationType.VLog, "Inventory.File.VLog.0650"),
    HbkLocation("Track 10: Graffiti #1 (WA-ES-2)", Regions.t10, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 10: Broken Armstrong Circuit #1", Regions.t10, HbkLocationType.Collectible, "St10/CircuitItem_BP1"),
    HbkLocation("Track 10: Life Gauge Piece #1", Regions.t10, HbkLocationType.Collectible, "St10/LifeCoreItem_BP1"),
    HbkLocation("Track 10: Broken Armstrong Circuit #2", Regions.t10, HbkLocationType.Collectible, "St10/CircuitItem_BP2"),
    HbkLocation("Track 10: VLog \"Atrium Statue Mail\"", Regions.t10, HbkLocationType.VLog, "Inventory.File.VLog.0660"),
    HbkLocation("Track 10: Broken Armstrong Circuit #3", Regions.t10, HbkLocationType.Collectible, "St10/CircuitItem_BP3"),
    HbkLocation("Track 10: Graffiti #2 (Wrench)", Regions.t10, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 10: Life Gauge Piece #2", Regions.t10, HbkLocationType.Collectible, "St10/np0600_BP_6"),
    HbkLocation("Track 10: SPECTRA Challenge Room", Regions.t10, HbkLocationType.SPECTRA, ""),
    HbkLocation("Track 10: Broken Armstrong Circuit #4", Regions.t10, HbkLocationType.Collectible, "St10/CircuitItem_BP4"),
    HbkLocation("Track 10: VLog \"Budget Challenge Mail\"", Regions.t10, HbkLocationType.VLog, "Inventory.File.VLog.0670"),
    HbkLocation("Track 10: Life Gauge Piece #3", Regions.t10, HbkLocationType.Collectible, "St10/LifeCoreItem_BP2"),
    HbkLocation("Track 10: Broken Armstrong Circuit #5", Regions.t10, HbkLocationType.Collectible, "St10/CircuitItem_BP5"),
    HbkLocation("Track 10: VLog \"Hoodie Preorder Mail\"", Regions.t10, HbkLocationType.VLog, "Inventory.File.VLog.0680"),
    HbkLocation("Track 10: Broken Piece of a Health Tank", Regions.t10, HbkLocationType.Collectible, "St10/LifeTankPieceItem_BP_6"),
    HbkLocation("Track 10: VLog \"Vandelay Handbook Note\"", Regions.t10, HbkLocationType.VLog, "Inventory.File.VLog.0690"),
    HbkLocation("Track 10: Graffiti #3 (Roquefort)", Regions.t10, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 10: Electric Reverb Core Piece", Regions.t10, HbkLocationType.Collectible, "St10/ReverbPieceItem_BP_2"),
    HbkLocation("Track 10: Graffiti #4 (Kale)", Regions.t10, HbkLocationType.Graffiti, ""),
    HbkLocation("Track 10: VLog \"Roquefort Meeting Prep\"", Regions.t10, HbkLocationType.VLog, "Inventory.File.VLog.0700"),
    HbkLocation("Track 10: Broken Armstrong Circuit #6", Regions.t10, HbkLocationType.Collectible, "St10/CircuitItem_BP6"),
    HbkLocation("Track 10: Completed", Regions.t10, HbkLocationType.TrackComplete, "cs1040_00"),

    HbkLocation("Track 11: Completed", Regions.t11, HbkLocationType.TrackComplete, "cs1130_00")
]